spring.application.name=crud-aop

# 데이터 소스
db.url=jdbc:mysql://localhost:3306/aloha?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
db.username=aloha
db.password=123456134653286714567485321674325167

# 로깅 레벨 설정
# 서버 콘솔 출력 색상 지정
spring.output.ansi.enabled=ALWAYS
# 전체 기본 로그 레벨
logging.level.root=INFO
# 프로젝트 패키지 로그 레벨 (디버깅 목적)
logging.level.com.aloha.crud=DEBUG
# 콘솔 출력 포맷 설정
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n

# 로그 파일
# 1. 로그 파일 경로 및 이름 지정
logging.file.name=logs/app.log
# 2. 개별 로그 파일 최대 크기 (기본값: 10MB)
logging.logback.rollingpolicy.max-file-size=10MB
# 3. 보관할 최대 로그 파일 일수 (기본값: 7일)
logging.logback.rollingpolicy.max-history=30
# 4. 전체 로그 파일 총 용량 제한
logging.logback.rollingpolicy.total-size-cap=1GB