plugins {
	id 'java'
	id 'war'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.aloha'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(23)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    // Spring
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    // MySQL
    runtimeOnly 'com.mysql:mysql-connector-j'
    // Tomcat
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat-runtime'

    // 테스트
    // JUnit, AssertJ, Mockito, Spring Test 등
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // JPA 테스트 (@DataJpaTest)
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    // MVC 테스트 (@WebMvcTest, MockMvc)
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    // 테스트용 Lombok
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    // JUnit Platform
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
    testLogging {

        // 테스트 결과 출력
        // passed        : 성공한 테스트 출력
        // failed        : 실패한 테스트 출력
        // skipped       : 건너뛴 테스트 출력
        // standardOut   : 테스트에서 System.out으로 출력한 내용
        // standardError : 테스트에서 System.err로 출력한 내용
        events "passed", "failed", "skipped", "standardOut", "standardError"

        // 테스트에서 발생한 표준 출력(System.out)과
        // 표준 오류(System.err)를 콘솔에 출력
        // → log.info() 등의 테스트 실행 로그를 확인할 때 사용
        showStandardStreams = true

        // 테스트 실패 시 예외 정보를 전체 형태로 출력
        // → 예외 메시지뿐만 아니라 Stack Trace까지 자세하게 확인
        exceptionFormat "full"
    }
}
